# Generated by Django 5.2.4 on 2025-08-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('education_level', models.CharField(choices=[('none', 'None'), ('olevel', 'O Level'), ('alevel', 'A Level'), ('diploma', 'Diploma'), ('bachelors', 'Bachelors Degree'), ('masters', 'Masters Degree'), ('phd', 'PhD')], max_length=20)),
                ('career_field', models.CharField(choices=[('software_engineer', 'Software Engineer'), ('data_scientist', 'Data Scientist'), ('web_developer', 'Web Developer'), ('network_admin', 'Network Administrator'), ('teacher', 'Teacher'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('accountant', 'Accountant'), ('lawyer', 'Lawyer'), ('engineer', 'Engineer'), ('mechanic', 'Mechanic'), ('chef', 'Chef'), ('pilot', 'Pilot'), ('artist', 'Artist'), ('musician', 'Musician'), ('entrepreneur', 'Entrepreneur'), ('architect', 'Architect'), ('pharmacist', 'Pharmacist'), ('civil_servant', 'Civil Servant'), ('journalist', 'Journalist'), ('other', 'Other')], max_length=50)),
            ],
        ),
    ]
