# Generated by Django 5.2.4 on 2025-08-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_country_userprofile_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='works_overseas',
            new_name='oversea',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='works_locally',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.CharField(default='Unknown District', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_done',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='career_field',
            field=models.CharField(choices=[('software_engineer', 'Software Engineer'), ('data_scientist', 'Data Scientist'), ('web_developer', 'Web Developer'), ('network_admin', 'Network Administrator'), ('teacher', 'Teacher'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('accountant', 'Accountant'), ('lawyer', 'Lawyer'), ('engineer', 'Engineer'), ('mechanic', 'Mechanic'), ('chef', 'Chef'), ('pilot', 'Pilot'), ('artist', 'Artist'), ('musician', 'Musician'), ('entrepreneur', 'Entrepreneur'), ('architect', 'Architect'), ('pharmacist', 'Pharmacist'), ('civil_servant', 'Civil Servant'), ('journalist', 'Journalist'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(choices=[('none', 'None'), ('olevel', 'O Level'), ('alevel', 'A Level'), ('diploma', 'Diploma'), ('bachelors', 'Bachelors Degree'), ('masters', 'Masters Degree'), ('phd', 'PhD')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(default='Unknown Region', max_length=50),
        ),
    ]
