# Generated by Django 5.2.5 on 2025-08-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_works_overseas_userprofile_oversea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
