# Generated by Django 5.2.4 on 2025-08-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='upload_cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
